Fix simd_word.u8 size (#96)
Also: really disable SSE2 and AVX2 when SIMD_WIDTH=64. On my machine SIMD_WIDTH=64 used to behave like SIMD_WIDTH=128 due `-msse2` enabled by default. I noticed this when the unit test failed to fail. I confirmed this by adding `#error` pre-processor instructions into simd_compat_{avx2,polyfill,sse2}.h:

Before the change to CMakeLists.txt:

```
14:54:23 viathor@ubik:~/src/stim$ cmake . -DSIMD_WIDTH=64
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/viathor/src/stim
14:54:45 viathor@ubik:~/src/stim$ make stim_test
[  0%] Building CXX object CMakeFiles/stim_test.dir/src/arg_parse.cc.o
[  0%] Building CXX object CMakeFiles/stim_test.dir/src/circuit/circuit.cc.o
In file included from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_compat.h:23,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_bits_range_ref.h:25,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_bits.h:24,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_bit_table.h:20,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/measure_record_writer.h:24,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/measure_record.h:23,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/tableau_simulator.h:28,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/circuit.cc:21:
/usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_compat_sse2.h:23:2: error: #error "sse2"
   23 | #error "sse2"
      |  ^~~~~
make[3]: *** [CMakeFiles/stim_test.dir/build.make:95: CMakeFiles/stim_test.dir/src/circuit/circuit.cc.o] Error 1
```

After:

```
15:00:17 viathor@ubik:~/src/stim$ cmake . -DSIMD_WIDTH=64
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/viathor/src/stim
15:00:37 viathor@ubik:~/src/stim$ make stim_test
[  0%] Building CXX object CMakeFiles/stim_test.dir/src/arg_parse.cc.o
[  0%] Building CXX object CMakeFiles/stim_test.dir/src/circuit/circuit.cc.o
In file included from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_compat.h:25,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_bits_range_ref.h:25,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_bits.h:24,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_bit_table.h:20,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/measure_record_writer.h:24,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/measure_record.h:23,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/../simulators/tableau_simulator.h:28,
                 from /usr/local/google/home/viathor/src/stim/src/circuit/circuit.cc:21:
/usr/local/google/home/viathor/src/stim/src/circuit/../simulators/../io/../simd/simd_compat_polyfill.h:22:2: error: #error "polyfill"
   22 | #error "polyfill"
      |  ^~~~~
make[3]: *** [CMakeFiles/stim_test.dir/build.make:95: CMakeFiles/stim_test.dir/src/circuit/circuit.cc.o] Error 1
```